version: '3.8'

services:
  db:
    container_name: db
    image: postgres:13
    restart: always
    environment:
        POSTGRES_PASSWORD: password
        POSTGRES_DB: reApp
    ports:
        - 15432:5432

  php-fpm:
    container_name: php-fpm
    image: vladislavnazarychev/re_app_test_nazarychev:re_app_v4
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./../src/:/var/www
      - ./php-fpm/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      - ./../src/:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"


